# container-based build
sudo: false

language: scala

git:
  quiet: true # (default = false)
  depth: 5 # (default = 50)

env:
  - JAVA_OPTS="-DSKIP_FLAKY=true -Dsbt.log.noformat=true"

# These directories are cached to S3 at the end of the build
cache:
  timeout: 300 # seconds = 5 mins (default = 3 mins)
  directories:
   - $HOME/.ivy2
   - $HOME/.sbt/boot/scala-$TRAVIS_SCALA_VERSION
   - $HOME/.dodo

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

scala:
  - 2.11.12
  - 2.12.4

jdk:
  - oraclejdk8

notifications:
  slack:
    secure: FfzYHh8IvtBaYswh9mIQU9yQGr9YpkRaFR77RaYdK5wVhw3UlCBtRTBdFpUn0djgg3Pl3FxEj5OyEKYQ803xxF7UQRxx298g4r5OhOzjQ4UH1lhnAg1WpIRPBL4DuWrreZFtnqvsygrdtvATZ1aLzaYtkaCV49x/t2Kr7weNfpQ=

before_script:
  - unset SBT_OPTS # default $SBT_OPTS is irrelevant to sbt launcher
  - travis_retry ./sbt --error ++$TRAVIS_SCALA_VERSION update

script:
  - travis_retry ./sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport
  - ./sbt ++$TRAVIS_SCALA_VERSION coverageAggregate

after_success:  # note this is run per job in the matrix but only the last run is kept by codecov.io.
  - bash <(curl -s https://codecov.io/bash)

stages:
  - dodo
  - test

jobs:
  include:
    - stage: dodo
      jdk: oraclejdk8
      script: curl -s https://raw.githubusercontent.com/twitter/dodo/develop/bin/build | bash -s -- --no-test twitter-server
