dist: trusty
sudo: required

language: scala

git:
  depth: 3
  quiet: true

env:
  - JAVA_OPTS="-Dsbt.log.noformat=true"

# These directories are cached to S3 at the end of the build
cache:
  directories:
   - $HOME/.ivy2/cache
   - $HOME/.ivy2/local/com.twitter
   - $HOME/.sbt
   - $HOME/.dodo

before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache  -name "ivydata-*.properties" -delete
  - find $HOME/.sbt         -name "*.lock"               -delete

scala:
  - 2.11.12
  - 2.12.8
  - 2.13.1

jdk:
  - openjdk8
  - openjdk11

matrix:
  # Does not allow for assigning a build result if the non-'allow_failures' targets are complete
  # because of https://travis-ci.community/t/receiving-too-many-emails/4888
  fast_finish: false
  allow_failures:
    - scala: 2.13.1

notifications:
  slack:
    secure: FfzYHh8IvtBaYswh9mIQU9yQGr9YpkRaFR77RaYdK5wVhw3UlCBtRTBdFpUn0djgg3Pl3FxEj5OyEKYQ803xxF7UQRxx298g4r5OhOzjQ4UH1lhnAg1WpIRPBL4DuWrreZFtnqvsygrdtvATZ1aLzaYtkaCV49x/t2Kr7weNfpQ=
    on_failure: change
    on_success: change

before_script:
  - unset SBT_OPTS # default $SBT_OPTS is irrelevant to sbt launcher
  - curl -s https://raw.githubusercontent.com/twitter/dodo/develop/bin/build | bash -s -- --no-test --scala-version $TRAVIS_SCALA_VERSION twitter-server

script:
  - travis_retry ./sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport

after_success:
  - ./sbt ++$TRAVIS_SCALA_VERSION coverageAggregate
  - bash <(curl -s https://codecov.io/bash)
