junit_tests(
  sources = rglobs("*.scala"),
  compiler_option_sets = {"fatal_warnings"},
  dependencies = [
    "3rdparty/jvm/junit",
    "3rdparty/jvm/org/mockito:mockito-all",
    "3rdparty/jvm/org/scalacheck",
    "3rdparty/jvm/org/scalatest",
    "finagle/finagle-base-http/src/main/scala",
    "finagle/finagle-core/src/main/scala",
    "finagle/finagle-http/src/main/scala",
    "twitter-server/server/src/main/scala",
    "twitter-server/slf4j-jdk14/src/main/scala",
  ],
)
