resources(
    sources = [
        "!**/*.pyc",
        "!BUILD*",
        "**/*",
    ],
    tags = [
        "bazel-compatible",
        "deprecated",  # Users are encouraged to use twitter-server/logback-classic instead
    ],
)
