# test twitter-server

junit_tests(name='scala',
  dependencies=[
    'twitter-server/src/test:base',
    'twitter-server/src/main/scala'
  ],
  sources=rglobs('*.scala'),
  resources=['twitter-server/src/test/resources']
)
