# base test dependencies

target(name='base',
  dependencies=[
    '3rdparty/jvm/junit',
    '3rdparty/jvm/org/mockito:mockito-all',
    '3rdparty/jvm/org/scalacheck',
    '3rdparty/jvm/org/scalatest',
    'twitter-server/server/src/main/scala'
  ],
)